### ISSUE TITLE
List of bounded floats generates out of bounds

### ISSUE THREAD

**Issue by isaacsanders** [pragdave/quixir#10]
On the master branch of this repo http://github.com/isaacsanders/histogrammar-elixir, I have a test case, `test/histogrammar/bin_test.exs`, that contains a list of bounded floats.

It seems as though the list just throws out my structure and returns 42 forever.

**Comment by isaacsanders** [comment]
I wasn't able to replicate the bug in a REPL with just Pollution, so part of me thinks it is related to the `ptest`substitution, but that is just a guess.

**Comment by pragdave** [comment]
Can I go ahead and close this?

**Comment by isaacsanders** [comment]
I wouldn't mind a point release, but I understand if you would rather not.

**Comment by pragdave** [comment]
'tis released. 0.9.2 of quixir and 0.9.1 of pollution.

Thanks again.

**Comment by isaacsanders** [comment]
:+1: happy to help, when I can manage the time to figure out the issue.
