### ISSUE TITLE
Shrinking from a choose() block ignores min/max parameters

### ISSUE THREAD

**Issue by aseigo** [pragdave/quixir#12]
A function exists which takes a list or an int, and contains a bug:

```
defmodule Demo do
  def list_or_int(input) when is_list(input), do: Enum.count input
  def list_or_int(input) when is_integer(input) and input > 0, do: -1
end
```

To test, we may do this:

```
  test "returns a positive integer value" do
    ptest input: choose(from: [list(of: positive_int(), min: 1), positive_int()]) do
      result = Demo.list_or_int input
      assert is_integer(result)
      assert result > 0
    end
  end
```

When the value 1 is passed to list_or_int, it will return a negative number. quixir will then attempt to shrink the value, but will try 0 as a possible value despite the generator being declared as a positive_int().

If the test drops the choose clause like this:

```
  test "returns a positive integer value" do
    ptest input: list(of: positive_int(), min: 1) do
      result = Demo.list_or_int input
      assert is_integer(result)
      assert result > 0
    end

    ptest input: positive_int() do
      result = Demo.list_or_int input
      assert is_integer(result)
      assert result > 0
    end
  end
```

Then it works as expected.

It therefore appears to be the choose(..) clause causing the min/max boundaries for the generator to be lost.

Code to reproduce attached.

[QuixirBugDemo.zip](https://github.com/pragdave/quixir/files/1152405/QuixirBugDemo.zip)

**Comment by pragdave** [comment]
Great bug report—thanks.

I just pushed 0.9.3 (and 0.9.2 of pollution) that should fix it.

Thanks again

Dave

**Comment by aseigo** [comment]
You are a scholar and a gentleman! Thanks for the quick fix ... now I can re-record episode 4 of Exploring Elixir this evening with this bug gone .. awesome. Cheers!
