### ISSUE TITLE
Issues Running With Espec

### ISSUE THREAD

**Issue by asummers** [pragdave/quixir#5]
We are currently using [ESpec](https://github.com/antonmi/espec) and having issues getting it to play nicely with Quixir. We are currently not sure which library is stepping on which, but the behavior we see is that if we bind a variable in `ptest` replacing `test` with `it`using any of

```
ptest var: int() do
```
```
ptest [var: int()] do
```
```
ptest [var: int()], [] do
```

we get 

```
warning: variable var is unused
```

My questions are:
1) What specifically does your library need out of the test lib in order to function properly? Examining the source, it looks like we have to try/rescue a different assert function, but aside from that, I don't see you relying on ExUnit functionality for a ton. Perhaps a common shim interface could be created to accommodate both/other libraries. 

2) Can you think of anything that Quixir might be doing that would be breaking ESpec?

3) Can you think of anything ESpec might be doing that would be breaking Quixir?

We plan on investigating this ourselves, but wanted to throw it on your radar to see if you had any hunches. I suspect the issue is with ESpec, personally.

**Comment by pragdave** [comment]
Are you using ptest as the immediate child of a describe block?

**Comment by asummers** [comment]
Pulling it out to a simple example, it seems to work fine for success cases. Not sure what we were doing in our test to cause that, but that's on our end, apologies. 

It would still be awesome to be able to have some sort of hook allowing us to override ExUnit specific behavior (startup, errors caught in [here](https://github.com/pragdave/quixir/blob/ddaf156a036999335e7064b80a4fb2d038036015/lib/quixir/props.ex#L51), for example). If you would like, I can close this and open a new one as a feature request for that to keep the discussion clean.

**Comment by pragdave** [comment]
To be honest, I'd look at a PR for this, but I doubt I'd do the work
myself, simply because I really can't give much love to espec (or rspec,
or...) I just don't get why people like writing

     it do: expect "abc" |> to(match ~r/b/)

instead of

      assert "abc" =~ ~r/b/
