### ISSUE TITLE
Incompatible with JUnitFormatter?

### ISSUE THREAD

**Issue by schnittchen** [pragdave/quixir#8]
I'm currently using JUnitFormatter for intergrating with CI.

Adding a single test file using Quixir had the effect that the `_build/test/lib/my_app/test-junit-report.xml`file is not generated any more.

**Comment by pragdave** [comment]
Could you give me any more information? Can you see where the
incompatibility is?

**Comment by schnittchen** [comment]
Hmm, sitting down over the problem after hours trying to reproduce, it had disappeared. Hope it stays that way :)

**Comment by pragdave** [comment]
Thanks for checking, and I'm glad it's working for you now.
